Added -b flag for pretty-bytes output
sindresorhus/gzip-size-cli pull request #2
Opened 2017-01-21 17:06 UTC by adamsiwiec

Added an optional `-b` for a more readable output without the need of piping the output through pretty-bytes. Also wrote a test for it and it passes

2017-01-22 20:45 UTC, sindresorhus requested changes

2017-01-22 20:45 UTC, sindresorhus commented on cli.js
> +const bytesFlag = cli.flags.b;
I would like a long flag too: `--pretty`. You can use the minimist `alias` option to create the short flag for it.

2017-01-22 20:45 UTC, sindresorhus commented on cli.js
> +
Don't do unrelated changes.

2017-01-22 20:45 UTC, sindresorhus commented on cli.js
> +const pb = require('pretty-bytes');
Use the full name.

2017-01-22 20:45 UTC, sindresorhus commented on cli.js
> +	if (bytesFlag) {
Can just be a ternary expression inside console.log

2017-01-22 20:45 UTC, sindresorhus commented on test.js
> +test('file', async t => {
Needs a better title

2017-01-22 20:45 UTC, sindresorhus commented on test.js
> +	t.is(parseInt(stdout, 10), gzipSize.sync(a));
This doesn't actually test that the output is pretty.

2017-01-23 01:13 UTC, adamsiwiec commented
Ok changes are made as requested.

2017-01-23 08:37 UTC, sindresorhus commented
You missed:

- https://github.com/sindresorhus/gzip-size-cli/pull/2#discussion_r97233172
- https://github.com/sindresorhus/gzip-size-cli/pull/2#discussion_r97233245

You also need to document the flag in cli.js and the help output in the readme. Should be formatted like this: https://github.com/sindresorhus/boxen-cli/blob/8f3335b4ded5cc410e28debd1f5c3c5303c95d1e/cli.js#L20

2017-01-23 08:37 UTC, sindresorhus requested changes

2017-01-23 08:37 UTC, sindresorhus commented on cli.js
> +source.pipe(fn.stream()).on('gzip-size', gzipSize => bytesFlag ? console.log(prettyBytes(gzipSize)) : console.log(gzipSize));
I think you misunderstood what I was asking. This is what I would like:

```js
source.pipe(fn.stream()).on('gzip-size', gzipSize => {
	console.log(bytesFlag ? pb(gzipSize) : gzipSize);
});
```

2017-01-23 08:37 UTC, sindresorhus commented on cli.js
> +const bytesFlag = cli.flags.pretty;
I don't really see the point of this variable. It doesn't make things any shorter or clearer.

2017-01-23 08:37 UTC, sindresorhus commented on cli.js
> +const input = cli.input[0] || cli.flags.pretty;
What's going on here?

2017-01-23 13:22 UTC, adamsiwiec commented on cli.js
> +source.pipe(fn.stream()).on('gzip-size', gzipSize => bytesFlag ? console.log(prettyBytes(gzipSize)) : console.log(gzipSize));
Ahh, I thought you wanted me to remove the function 😀

2017-01-23 13:31 UTC, adamsiwiec commented on cli.js
> +const input = cli.input[0] || cli.flags.pretty;
So basically, this is to make sure you can do `gzip-size --pretty blah.js` or `gzip-size blah.js --pretty`. Basically just convenience for the user. You see this sort of thing in other packages like `npm install ava -g` or `npm install -g ava`

2017-01-23 13:35 UTC, adamsiwiec commented on cli.js
> +const bytesFlag = cli.flags.pretty;
It becomes necessary when you realize that you need a boolean flag for the ternary expression below AND that you need the `|| cli.flags.pretty` if the user inputs the file after the `--pretty` (`cli.input[0]` will not have any value in this case).

2017-01-23 13:49 UTC, sindresorhus commented on cli.js
> +const input = cli.input[0] || cli.flags.pretty;
Ok. You can solve that much elegantly with:

```js
const cli = meow(`
	Usage
	  $ gzip-size <file>
	  $ cat <file> | gzip-size

	Example
	  $ gzip-size index.js
	  211
`, {
	boolean: ['pretty']
});
```

2017-01-23 13:52 UTC, sindresorhus commented on cli.js
> +const bytesFlag = cli.flags.pretty;
`bytesFlag` is only used once

2017-01-23 14:01 UTC, closed without merging

2017-01-23 14:03 UTC, sindresorhus commented
I appreciate the PR, but I decided to make it pretty by default, and was just easier to do it myself.